# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3aH1Y38Lzb-xmWCdmqqRmzCfy5Z5zZo
"""

print("abc")
