# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_kAAVDJZBwN1JmCmWXCW5VIEjGQG7qv
"""

n = 7
print(n*n)